before_script:
    - apt-get update -qq
    - git clone https://github.com/bats-core/bats-core.git /tmp/bats
    - mkdir -p /tmp/local
    - bash /tmp/bats/install.sh /tmp/local
    - export PATH=$PATH:/tmp/local/bin
    - apt-get install libcunit1 libcunit1-doc libcunit1-dev

build:
    stage: build
    script:
        - make

test:
    stage: test
    script:
        - make test


